Move navlink component to nav repository
selsa-inube/inubekit-nav pull request #3
Opened 2024-03-12 17:01 UTC by cmarin001

This pull request outlines the strategic migration of the `<NavLink/>` component from its current location into the dedicated `<Nav/>` repository within our application's codebase. Aimed at bolstering modularity, simplifying component management, and fostering a more organized code structure, this move aligns with our ongoing efforts to optimize development workflows and enhance codebase coherence.

2024-03-12 18:40 UTC, JanuarAsprilla commented on package.json
>      "@inubekit/foundations": "^1.1.2",
This extension should not go in peerDependences

2024-03-12 19:59 UTC, JanuarAsprilla approved these changes

2024-03-14 16:22 UTC, wfercanas requested changes

2024-03-14 16:22 UTC, wfercanas commented on src/index.ts
>  export { Nav } from "./Nav";
Nav component still uses `@inubekit/navlink`

2024-03-14 16:57 UTC, wfercanas approved these changes

2024-03-14 16:57 UTC, merged