Adjust and export interfaces
selsa-inube/inubekit-nav pull request #6
Opened 2024-03-21 21:39 UTC by JanuarAsprilla

The names of the interfaces used by the `<Nav />` component were refactored, as well as how they are exported.

2024-03-26 15:37 UTC, wfercanas requested changes

2024-03-26 15:37 UTC, wfercanas commented on src/Nav/index.tsx
> +interface ILinkINavLink {
This interface could be just INavLink

2024-03-26 15:37 UTC, wfercanas commented on src/Nav/index.tsx
> +interface ILinkINav {
The interface was correct. Its name should be `INav`

2024-03-26 15:37 UTC, wfercanas commented on src/Nav/index.tsx
> +interface ILinkINavigation {
This component is Nav, so the interfaces should append `INav` before the name of the interface, not `ILink`. It applies to:
1. ISection
2. INavigation

Even more, is enough if you just use one `I`. For example: `INavSection` is enough, you don't need to repeat `INavISection`

2024-03-26 15:37 UTC, wfercanas commented on src/Nav/index.tsx
> +const MultiSections = ({ navigation }: Pick<ILinkINav, "navigation">) => {
There is no need to use a Pick here if we have all the interfaces available. You can just use `INavNavigation`

2024-03-26 15:37 UTC, wfercanas commented on src/Nav/index.tsx
> +const OneSection = ({ navigation }: Pick<ILinkINav, "navigation">) => {
Just use INavNavigation

2024-03-26 15:44 UTC, JanuarAsprilla commented on src/Nav/index.tsx
> +interface ILinkINavLink {
solved

2024-03-26 15:45 UTC, JanuarAsprilla commented on src/Nav/index.tsx
> +interface ILinkINav {
solved

2024-03-26 15:52 UTC, JanuarAsprilla commented on src/Nav/index.tsx
> +interface ILinkINavigation {
solved

2024-03-26 16:01 UTC, JanuarAsprilla commented on src/Nav/index.tsx
> +const MultiSections = ({ navigation }: Pick<ILinkINav, "navigation">) => {
solved

2024-03-26 23:00 UTC, wfercanas requested changes
In vite.config.ts we have to use "react-icons/md", without the `md` the build size is 11kb, while with the md the build size is 7kb.

2024-04-01 20:16 UTC, wfercanas approved these changes

2024-04-01 20:16 UTC, merged